#!/bin/bash

WORKDIR=/home/apetrishchev/Portable/Projects/github.com/APetrishchev/Laucher

# export GO111MODULE=on
# unset GOPATH
# cd "$WORKDIR/src/Application/1.0.0"
# go mod init httpServer_
# go mod tidy
# go list

export GO111MODULE=off
export GOPATH=$WORKDIR

go get github.com/google/uuid
# go get github.com/gorilla/securecookie
# go get github.com/go-gem/sessions
# go get github.com/valyala/fasthttp
# go get github.com/valyala/fasthttp/fasthttpadaptor
# go get github.com/mattn/go-sqlite3
# go get golang.org/x/crypto/acme/autocert
# go get golang.org/x/net/webdav
# go get gopkg.in/ini.v1
# @latest

export GOBIN=/home/apetrishchev/Portable/data/admin/exe
go install "$WORKDIR/src/Application/1.0.0/server.go"
# cat /home/apetrishchev/Portable/data/admin/.passwd | sudo --stdin "$GOBIN/server"

# export GOBIN=/home/apetrishchev/Portable/data/applications/HomeServer/1.0.0/linux_amd64
# go install "$WORKDIR/src/AppHomeServer/1.0.0/agent.go"
# "$GOBIN/agent"
