#!/bin/bash

WORKDIR=/home/apetrishchev/Portable/Projects/github.com/APetrishchev/Laucher/AppHomeServer/1.0.0
export GOBIN="$WORKDIR/back"
export GOPATH="$WORKDIR/_devel_"

go get "gopkg.in/ini.v1"
go get "github.com/valyala/fasthttp"

go install "$GOPATH/src/cmd/agent"

"$GOBIN/agent"
