#!/bin/bash

WORKDIR=/home/apetrishchev/Portable/Projects/apetrishchev.github.io/Application/1.0.0
export GOBIN="$WORKDIR/back"
export GOPATH="$WORKDIR/_devel_"

go get "gopkg.in/ini.v1"
go get "github.com/valyala/fasthttp"
go get "golang.org/x/crypto/acme/autocert"
go get "github.com/valyala/fasthttp/fasthttpadaptor"
go get "golang.org/x/net/webdav"

go install "$GOPATH/src/cmd/server"

# cat /home/apetrishchev/Portable/Projects/apetrishchev.github.io/.passwd | sudo --stdin "$GOBIN/server"
