#!/bin/bash

WORKDIR=/home/apetrishchev/Portable/Projects/github.com/APetrishchev/Laucher/Application/1.0.0
DEVDIR="$WORKDIR/_devel_"
export GOBIN="$WORKDIR/back"

go get gopkg.in/ini.v1@latest
go get github.com/valyala/fasthttp@latest
go get golang.org/x/crypto/acme/autocert@latest
go get github.com/valyala/fasthttp/fasthttpadaptor@latest
go get golang.org/x/net/webdav@latest
go get github.com/apetrishchev/laucher/application/1.0.0/_devel_/server

# go mod download gopkg.in/ini.v1
# go mod download github.com/valyala/fasthttp
# go mod download golang.org/x/crypto


export GO111MODULE=on
go install "$DEVDIR/server.go"

# export GO111MODULE=off
# export GOPATH=$DEVDIR
# go install "$DEVDIR/src/cmd/server"

# cat /home/apetrishchev/Portable/Projects/github.com/APetrishchev/Laucher/.passwd | sudo --stdin "$GOBIN/server"
